version: '3.5'
services:
  db:
    image: poc/monitor-dashboard
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    working_dir: /docker/mysql
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: projeto
    ports:
      - "3308:3306"
    networks:
      - rest-network
  monitor_dashboard:
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIRONMENT: Production
    volumes:
      - . monitor_dashboard
      - ~/.m2:/root/.m2
    ports:
      - "8080:8080"
    command: mvn clean spring-boot:run
    links:
      - db
    depends_on:
      - db
    networks:
      - rest-network
networks:
  rest-network:
    driver: bridge